# Generated by Django 6.0.7 on 2026-07-23 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=200)),
                ('region', models.CharField(choices=[('tunisia', 'tunisia'), ('germany', 'germany')], max_length=20)),
                ('state', models.CharField(choices=[('running', 'running'), ('charging', 'charging'), ('docked', 'docked'), ('maintenance', 'maintenance'), ('offline', 'offline')], max_length=20)),
                ('current_mission', models.CharField(blank=True, max_length=200, null=True)),
                ('battery', models.PositiveSmallIntegerField()),
                ('commissioned_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('client', 'client')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('assigned_robots', models.ManyToManyField(blank=True, related_name='assigned_users', to='pguard.robot')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rounds', models.PositiveIntegerField(default=0)),
                ('incidents', models.PositiveIntegerField(default=0)),
                ('charges', models.PositiveIntegerField(default=0)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='pguard.robot')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('robot', 'date')},
            },
        ),
    ]
