# Generated by Django 6.0.7 on 2026-07-23 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pguard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('disponibilite', models.FloatField()),
                ('autonomie', models.FloatField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to='pguard.robot')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('robot', 'date')},
            },
        ),
    ]
