# Generated by Django 6.0.7 on 2026-07-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pguard', '0002_dailykpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('obstacle', 'obstacle'), ('emergency_stop', 'emergency_stop'), ('docking_failed', 'docking_failed'), ('system', 'system')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critical', 'critical')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('mission_id', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(max_length=200)),
                ('desc_key', models.CharField(blank=True, max_length=60, null=True)),
                ('media_url', models.CharField(blank=True, max_length=200, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pguard.robot')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('resolved', 'resolved'), ('unresolved', 'unresolved')], max_length=10)),
                ('note', models.TextField()),
                ('resolved_by', models.CharField(max_length=100)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='pguard.alert')),
            ],
        ),
    ]
