# Generated by Django 6.0.7 on 2026-07-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pguard', '0003_alert_alertresolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('7d', '7d'), ('30d', '30d'), ('custom', 'custom')], max_length=10)),
                ('format', models.CharField(choices=[('pdf', 'pdf'), ('csv', 'csv')], max_length=10)),
                ('generated_at', models.DateTimeField()),
                ('size_kb', models.PositiveIntegerField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pguard.robot')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
