# Generated by Django 6.0.7 on 2026-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pguard', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
